name: C/C++ CI
permissions:
  contents: read
  id-token: write
  pull-requests: write

on:
  push:
    branches: 
        - main
        - bonus
  pull_request:
    branches: 
        - main
        - bonus

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libx11-dev \
          libglfw3-dev \
          libglfw3 \
          xorg-dev
    
    - name: make
      run: make
    
    - name: make check
      run: make check
    
    - name: make bundle
      run: make bundle

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: so_long
        path: build/so_long.tar.gz
